### PR TITLE
chore: release 1.1.0

### PR DESCRIPTION
**Pull request by JustinBeckwith**
[release notes](https://github.com/ofrobots/require-so-slow/releases/edit/untagged-f96902caf2b8607cc7d9)

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
Mostly because I want to use this right now and I can't 😆

**Comment by JustinBeckwith** [comment]
wait wait wait

**Comment by JustinBeckwith** [comment]
ok go again 😸

**Comment by ofrobots** [comment]
Lgtm

**Pull request merged**
